In [1]:
import torch

### Data Creation and data info gathering

By invoking arange(n), we can create a vector of evenly spaced values, starting at 0 and ending at n.

In [2]:
x = torch.arange(12, dtype = torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

**numel** method is like the len operator

In [3]:
x.numel()

12

Similar to the **shape** method in numpy

In [4]:
x.shape

torch.Size([12])

And, the **reshape** method

In [8]:
X = x.reshape(4,3)
X

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

And the same is for initializing **zeros** and **ones**

In [9]:
torch.zeros((2,3,5))

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [10]:
torch.ones((2,5,5))

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

And, we can sample each element randomly from a given probability distribution. The following snippet creates a tensor with elements from a normal distribution.

In [11]:
torch.randn(3,3)

tensor([[-0.0742, -0.6094,  0.1738],
        [ 0.1788,  0.8581,  1.5082],
        [ 0.7539,  0.9711,  0.4537]])

And, Finally we can construct tensors by providing the elements we need by initializing them inside a python lists containing numerical literals.

In [12]:
torch.tensor([[1,2,3],[4,5,6],[7,9,9]])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 9, 9]])

### Indexing and Slicing

Accessing tensor elements is very similar to how you access elements inside a list.

In [13]:
X[-1]

tensor([ 9., 10., 11.])

In [15]:
X[0:2]

tensor([[0., 1., 2.],
        [3., 4., 5.]])

We can acess a particular element by specifying the various dimension inside the tensor like:

In [16]:
X[0,2] = 999

In [17]:
X

tensor([[  0.,   1., 999.],
        [  3.,   4.,   5.],
        [  6.,   7.,   8.],
        [  9.,  10.,  11.]])

In [18]:
X[:3,:] = 888.

In [19]:
X

tensor([[888., 888., 888.],
        [888., 888., 888.],
        [888., 888., 888.],
        [  9.,  10.,  11.]])

In [20]:
X.shape

torch.Size([4, 3])

### Operations

Most standard operators such as unary operator like e^x can be applied elementwise.

In [21]:
torch.exp(x)

tensor([       inf,        inf,        inf,        inf,        inf,        inf,
               inf,        inf,        inf,  8103.0840, 22026.4648, 59874.1406])

As for the binary scalar operations, we can produce a new vector or tensor from providing two tensors of the same shape. These also happen elementwise for identically shaped tensors of arbitrary shape.

In [24]:
A = torch.ones(2,3)
B = torch.ones(2,3)
A = A + B
A

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [25]:
A-B, A*B, A**B, A/B

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[2., 2., 2.],
         [2., 2., 2.]]),
 tensor([[2., 2., 2.],
         [2., 2., 2.]]),
 tensor([[2., 2., 2.],
         [2., 2., 2.]]))

In addition to unary or binary single element-wise operations, we can also perform linear algebric operations like dot product or matrix multiplication. More on this later.

Additionally, we can concatenate multiple tensors, stacking them end-to-end to form a larger one. After providing a list of tensors, we can tell the system axis through which to concatenate.

In [72]:
X = torch.arange(12, dtype = torch.float32).reshape(3,4)
Y = torch.zeros(3,4)
torch.cat((X,Y), dim = 0), torch.cat((X,Y), dim = 1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]]),
 tensor([[ 0.,  1.,  2.,  3.,  0.,  0.,  0.,  0.],
         [ 4.,  5.,  6.,  7.,  0.,  0.,  0.,  0.],
         [ 8.,  9., 10., 11.,  0.,  0.,  0.,  0.]]))

We can also contruct a binary tensors via logical statements. 

In [58]:
boo = (X <= Y)
boo

tensor([[ True, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

And we can sum the whole tensor

In [28]:
X.sum()

tensor(120.)

In [31]:
boo.sum()  # although boo waas a tensors of True or False, it treated True as 1.

tensor(15)

### Broadcasting

Under certain conditions, even though when shapes differ, we can still perform elementwise binary opeartions by invoking the **broadcasting** mechanism. 

In [43]:
a = torch.arange(6).reshape(2,3)
b = torch.arange(3)
a,b

(tensor([[0, 1, 2],
         [3, 4, 5]]),
 tensor([0, 1, 2]))

In [44]:
a+b

tensor([[0, 2, 4],
        [3, 5, 7]])

### Saving Memory

Running operations can cause new memory to be allocated to host results. We want to save memory so we want to update the variable pointing to the tensor in place. 

In [45]:
before = id(a)
a = a+b
before == id(a)

False

We need to update the variables in place for two mainly two reasons:
- we have multiple parameters that are updated per very small unit time so allocating new memory for each isn't efficient and very costly
- Multiple other variables might be pointiing to a single variable and we need to update the references if we don't update in place.

We can use slice notation to perform in-place operations

In [46]:
before = id(a)
a[:] = a+b 
before == id(a)

True

Alternatively, we can use operators like this instead of slicing too

In [51]:
before = id(a)
a =+ b
before == id(a)

True

### Conversion to other Python Objects

We can change from a numpy darray to tensor and vice versa and they share the same memory. So, changing them with in-place operator will change the other. 

In [74]:
import numpy as np
A = np.zeros(5)
B = torch.from_numpy(A)
print(id(A), id(B))
print(id(A) == id (B))
type(A), type(B)

1871462109456 1871461732816
False


(numpy.ndarray, torch.Tensor)

To convert a size-1 tensor to a python scalar, we can invoke the **item** function or python's in-built functions

In [55]:
y = torch.tensor([1])
y,y.item(),float(y), int(y)

(tensor([1]), 1, 1.0, 1)

### Extras

In [67]:
a_1 = torch.ones(2,3,5)
b_1 = torch.ones(2,1,1)
a_1,b_1

(tensor([[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]]),
 tensor([[[1.]],
 
         [[1.]]]))

In [68]:
a_1 + b_1

tensor([[[2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.]],

        [[2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.]]])